# Generated by Django 4.2.11 on 2024-06-16 21:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_upload_images_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_images',
            name='likes',
            field=models.ManyToManyField(related_name='image_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
