# Generated by Django 4.2.11 on 2024-06-20 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_upload_images_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.upload_images'),
        ),
    ]
